#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: klaushartl
 * Date: 12.11.2016
 */

use Symfony\Component\Console\Application;
use Transkriptor\Command\TranscribeCommand;


if ( ! $loader = include __DIR__ . '/../vendor/autoload.php' ) {
	die( 'You must set up the project dependencies.' );
}

$app = new Application( 'PHP Natural Language Transkriptor by <k127@gmx.de>', '@package_version@' );

// Transkriptor
$app->add( new TranscribeCommand() );

$app->run();
